### ISSUE TITLE
"Filter button"

### ISSUE THREAD

**Issue by rafaelfcponde** [NikolayXHD/Mtgdb#13]
So, in my experience, the way the filtering tool is just takes up a lot of space, which could be better used. Also, in smaller screens, it could actually be a nuisance.

My suggestion is that, instead of having it as multiple rows in the raw UI, you could have a "Filter button", which would bring up an extra window with the filtering options.

**Comment by NikolayXHD** [comment]
I see your point about the space, especially in smaller screen. My solution would be to make the filter panels hide-able so you can use the space they occupy for other purposes.

Showing / hiding the filter panels would be done using an additional button in window title
![window title](https://github.com/NikolayXHD/Mtgdb/raw/master/out/help/l/header_buttons.jpg)

I intentionally avoid separate window solution it as *implicit* as opposed to *explicit* filter panels.

Searching / filtering is the essential feature of Mtgdb.Gui, because all other features 
- either require the search to be done, like deck building, diagrams, an etc.
- are required mainly to make the search possible, like import or manually input collection.

Being an essential feature, searching / filtering must be *explicit* thus having the following advantages:
- You can see all the factors that are affecting search result *and* the search result simultaneously. This helps avoid confusion about why are you observing certain search result. The confusion I am talking about is a practical (not theoretical) thing. Even the explicit way the filters are now, I often get confused about why the current search result is empty.
- You *allways* see *all* options you have to affect the search result.
- You are by 1 click closer from doing the change, by 1 mental step closer to thinking about it.
- New users are by 1 discovery closer to learning about the filters, because they are not hidden.

**Comment by NikolayXHD** [comment]
fixed in 3.1.0.8
