### ISSUE TITLE
Regular Settings Window

### ISSUE THREAD

**Issue by rafaelfcponde** [NikolayXHD/Mtgdb#14]
When you click on "General Settings", it brings up a browser window with an XML code. The user is supposed to rewrite such code to change the settings in his/her app.

Having a regular Settings Window pop-up is a lot more user friendly (as well as more visually pleasing)

**Comment by NikolayXHD** [comment]
Mtgdb.Gui opens the settings file using whatever program your Operating System has assigned to open *.xml files. In case you are willing to tweak the settings, you should assign `*.xml` file extension to your text editor, instead of internet browser, because browser is rather a *viewer* than *editor*. Then in text editor you will be able to edit and save your changes.

It is true that tweaking those settings requires you to be a quite an advanced PC user, a computer geek, programmer, tester, some other IT guy (or girl :smiley:).

Not-so-advansed things that were initially in settings have with time converted to User Interface elements, i am mainly referring these:
![display settings](https://raw.githubusercontent.com/NikolayXHD/Mtgdb/master/out/help/l/display_settings.jpg)

With advanced settings having a User Interface does not really bring an improvement. The fact you *need* to change these settings pretty much implies you *can* do this by editing *.xml file,
then any good text editor (such as Notepad++) is more straightforward and comfortable than any
User Interface I could possibly provide within Mtgdb.Gui with a reasonable effort.

What is left is really *advanced* and I should rename them from not `General Settings` to `Advanced Settings`.
