### ISSUE TITLE
Customizable tab system

### ISSUE THREAD

**Issue by rafaelfcponde** [NikolayXHD/Mtgdb#15]
This is more of a suggestion than an issue, and I believe it can be quite challenging to pull off. However, I believe it can make the app stand out among the other collection manager apps.

Instead of the "TDI system" that's being used today, I'm thinking of making the app as like a big white board in which you can bring multiple windows, to maximize user customization (and boost practicality).

It would work something like the Fruity Loops UI: when you open the app, it would be empty, with just the superior row for tab selection and other options. From there, you could prompt the app to open windows specifically for the things you want to work on (a Deck window, a Collection window, a Search window, a Selected Card Details window, etc).
Those windows would be each scalable and customizable on their own (this way, the user could choose how he wants his interface to look like, both to enhance aesthetics and boost usability).
The tabs would be used to manage multiple "white boards".

**Comment by NikolayXHD** [comment]
Thank you for explaining your idea in such great details. Suggestions are a valid and welcome type of issue.

I can see how Whiteboard approach can be useful by example of Forge
![screenshot](https://www.slightlymagic.net/forum/download/file.php?id=28557&mode=view)

As a sidenote, it requires scalable card images (which you already pointed  in #2 which I separated to #5) in order to effeciently display cards in smaller panels

Now, I agree with your estimation that of that being 
> quite challenging to pull off

So, to justify the effort  in particular case of Mtgdb.Gui, there have to be examples of layouts (filled Whiteboards) with following properties:
- It greatly improves convenience for doing some task over the current UI
- The improvement cannot be achived by modifying the current non-customizable UI without making it worse for other important tasks.

I am talking about specific Mtgdb.Gui layout examples for a reason. While generally speaking Whiteboard approach has its benefits, it should not be assumed those benefits can universally improve any program.

Specific layout examples show how keeping a single layout may not be the best long-term option specifically for Mtgdb.Gui.

Provided such examples are given, there is still an option of giving several non-customizable layouts for users to choose from. Such an approach would have advantages over customizable UI:
- They are available to users out-of-the box
- All users share the benefits while these layouts are being improved based on users feedback, which also comes from many users instead of the single person who has created for himself.

**Comment by NikolayXHD** [comment]
Versions [3.2.0.0](https://github.com/NikolayXHD/Mtgdb/wiki/Release-notes#3200) and [3.2.1.0](https://github.com/NikolayXHD/Mtgdb/wiki/Release-notes#3210) introduced Multi-window support with window position preserving between restarts and ability to drag-n-drop *cards* and *tabs* between windows.

Combined with previously existing possibilites to hide filter panels and deck area, these give you a degree of control over your screen layout comparable to what Whiteboard approach would give.
