### ISSUE TITLE
Feature request: List views for collection etc.

### ISSUE THREAD

**Issue by paulsnoops** [NikolayXHD/Mtgdb#74]
Feature request
===============

Would it be possible to get list views for all areas but especially collection?

**Comment by NikolayXHD** [comment]
For any workflow, that benefits from table-like presentation, I would suggest resorting to copy-paste / export features of Mtgdb.Gui, so that you get a spredsheet and work with it in any other application.

If this would be helpful to you, I am ready to discuss what data needs to be in that spreadsheet and possibly improve existing copy / paste / export so that you can have the spreadsheet with the data you need.

**Comment by paulsnoops** [comment]
That's completely fair and understandle, so no worries!

I already have my colletion database elsewhere and in a spreadsheet, it was more a suggestion as an option inside the app but I can see how difficult it's going to be to implement but thank you for your reply!

I will close this issue, thanks again :)
